language: node_js
sudo: required
node_js:
  - "lts/carbon"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install -g @ui5/cli
  - npm install
script:
  - npm run test-ci
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
